apiVersion: v1
kind: Namespace
metadata:
  name: inflate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: inflate
spec:
  replicas: 10
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "250m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "100Mi"
