apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-static-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/heschmat/devops_eks_portfolio.git
    targetRevision: HEAD
    path: helm/go-static-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: go-static-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
