name: "GHCR Login"
description: "Log in to GitHub Container Registry with GH_PAT or fallback to GITHUB_TOKEN"
inputs:
  registry:
    description: "Container registry"
    required: false
    default: "ghcr.io"
  username:
    description: "Registry username"
    required: false
    default: ${{ github.actor }}
runs:
  using: "composite"
  steps:
    - name: Log in to GHCR
      shell: bash
      run: |
        echo "🔐 Logging into ${{ inputs.registry }} as ${{ inputs.username }}"

        if [ -n "${{ secrets.GH_PAT }}" ]; then
          echo "${{ secrets.GH_PAT }}" | docker login ${{ inputs.registry }} \
            -u "${{ inputs.username }}" --password-stdin
          echo "✅ Authenticated with GH_PAT"
        else
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ inputs.registry }} \
            -u "${{ inputs.username }}" --password-stdin
          echo "✅ Authenticated with GITHUB_TOKEN"
        fi
