apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-go
  namespace: argocd
spec:
  destination:
    namespace: go-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/heschmat/devops_eks_portfolio.git
    targetRevision: HEAD
    path: helm/go-static-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
