name: Test GHCR Login

on:
  workflow_dispatch:   # run manually from the Actions tab

jobs:
  test-login-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: heschmat
          password: ${{ secrets.GH_PAT }}

      - name: Show Docker config
        run: |
          echo "== Docker info =="
          docker info
          echo
          echo "== Docker config.json =="
          cat ~/.docker/config.json | jq .
          echo
          echo "== GitHub API user =="
          curl -s -H "Authorization: Bearer ${{ secrets.GH_PAT }}" https://api.github.com/user | jq .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push test image
        run: |
          echo "FROM alpine:3.19\nCMD [\"echo\", \"Hello from GHCR!\"]" > Dockerfile
          docker buildx build . \
            -t ghcr.io/heschmat/test-image:test \
            --push
